server:
  port: 34102
spring:
  application:
    name: vlp-course-service
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/vlp?createDatabaseIfNotExist=true&serverTimezone=UTC
    user: vlp
    password: vlp
    locations: "classpath:/flyway/scripts/migration"
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/vlp?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: vlp
    password: vlp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
management:
  server:
    port: 44102
logging:
  level:
    net.ttddyy.dsproxy.listener: debug